### ISSUE TITLE
Unleashed firmware crash

### ISSUE THREAD

**Issue by enty8080** [noproto/apple_ble_spam_ofw#1]
After launching the spam attack, flipper crashed with `NULL pointer dereference`.

Firmware version: [flipper-z-f7-update-unlshd-062e.tgz](https://github.com/DarkFlippers/unleashed-firmware/releases/download/unlshd-062/flipper-z-f7-update-unlshd-062e.tgz)

**Comment by maxdauner** [comment]
I have to add, that the same problem occurs by me with the OFW at the latest Release 0.90.1

**Comment by noproto** [comment]
WIP stands for work in progress. I was aware of this issue when I shared the code while is currently under development. It isn't ready yet but a thousand people have downloaded it in the past 2 days. I spent the past 48 hours tracking down the issue and I hope to have it resolved soon.

**Comment by enty8080** [comment]
@noproto I suggest you to refer to Flipper Zero Xtreme firmware. They are currently developing the app for Apple BLE spamming in dev branch too. Moreover, I installed their dev builds and the app there worked.

Here is the link: https://github.com/Flipper-XFW/Xtreme-Firmware/tree/dev/applications/external/apple_ble_spam

**Comment by noproto** [comment]
Fixed
