### ISSUE TITLE
Flipper Crashes after any attack

### ISSUE THREAD

**Issue by Obsideaock** [noproto/apple_ble_spam_ofw#2]
When I try any of the attacks given in the app , it turns for a tenth of a second, then crashes and when it restarts says that it was ‘BusFault’

Any help would be appreciated
Thank you!

**Comment by noproto** [comment]
Are you using the official firmware, version 0.90.1?

**Comment by leedave** [comment]
Works for fine for me on 0.90.1
It seems a little less efficient as on cfw, 

- less attacks seem to trigger messages on my iPhone 
- Messages seem to reappear less frequent.

All in all I'm glad to have a working solution on ofw. Thanks for porting it.

**Comment by noproto** [comment]
@Obsideaock Please try with the latest release.
