### ISSUE TITLE
API Mismatch Problem on Xtreme firmware 

### ISSUE THREAD

**Issue by Hamika20** [noproto/apple_ble_spam_ofw#3]
After I launch the app on the Xtreme Firmware I get this Screen saying this : 
Any Ideas how to fix this? 
![Screenshot-20230918-185721](https://github.com/noproto/apple_ble_spam_ofw/assets/122438385/787b324e-09cd-47c4-b36e-1e2f199b4bbf)

**Comment by noproto** [comment]
This repository is not for the XFW application developed by WillyJL. XFW includes their own version. Please report issues in XFW to https://github.com/Flipper-XFW/Xtreme-Firmware.
