### ISSUE TITLE
Usage Fault on last release

### ISSUE THREAD

**Issue by hhartz** [noproto/apple_ble_spam_ofw#4]
Last release crashes with usage fault error when initiating an action

**Comment by noproto** [comment]
Known issue, the API was refactored so the offset has changed. I'll fix the app within the next week. In the meantime, if you'd like to continue to use the app, please use an earlier OFW release.

**Comment by ChopsKingsland** [comment]
@noproto, where can I find an older compiled .fap file, as there is not one in this repo?

**Comment by RogueMaster** [comment]
My public release has it working if you want to try that

**Comment by ChopsKingsland** [comment]
@RogueMaster is it part of your firmware, or is there a separate .fap?

**Comment by RogueMaster** [comment]
It's part of the firmware and a separate fap that will only work on custom firmware. Due to changes in the API to have it work, it won't work on OFW. When noprotos work around is completed it will work on OFW

**Comment by noproto** [comment]
Try now.

**Comment by noproto** [comment]
Tested with no issues with the new FAP release. Please open a new issue if you run into additional errors.
